<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>fr.damnardev.template.maven.spring</groupId>
		<artifactId>maven-spring-boot-template-internal-parent</artifactId>
		<version>1.0.0-SNAPSHOT</version>
		<relativePath>../maven-spring-boot-template-internal-parent/pom.xml</relativePath>
	</parent>

	<artifactId>maven-spring-boot-template-cli</artifactId>
	<packaging>jar</packaging>

	<name>Maven Spring Boot Template - CLI</name>
	<description>Command-line interface for the Maven Spring Boot template</description>

	<dependencies>
		<dependency>
			<groupId>fr.damnardev.template.maven.spring</groupId>
			<artifactId>maven-spring-boot-template-common</artifactId>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<mainClass>fr.damnardev.template.maven.spring.cli.Startup</mainClass>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
